[tools]
usage = "latest"
ruby = "latest"
rust = "latest"
python = "latest"
bun = "latest"
"cargo:ivm" = "latest"
erlang = "28"
elixir = "1.19"
yarn = "latest"
"npm:@herb-tools/language-server" = "0.5.0"
"npm:@mermaid-js/mermaid-cli" = "latest"
"npm:@github/copilot" = "latest"
watchexec = "latest"
node = "latest"
"gem:referral" = "0.0.5"
gleam = "1.13.0"

[settings]
experimental = true

[env]
OVERMIND_SKIP_ENV = "true"
OVERMIND_PROCFILE = "Procfile.dev"
OVERMIND_NO_PORT = 1
PGGSSENCMODE = "disable"
